---
argument_specs:
  main:
    short_description: Entry point for the chrony role.
    description:
    - Validate variables for the `chrony` role.
    options:
      chrony_set_time_zone:
        description:
        - Controls `chrony_set_time_zone` for the `chrony` role.
        required: false
        type: bool
      chrony_timezone:
        description:
        - Controls `chrony_timezone` for the `chrony` role.
        required: false
        type: str
      chrony_manage_ntp:
        description:
        - Controls `chrony_manage_ntp` for the `chrony` role.
        required: false
        type: bool
      chrony_manage_service:
        description:
        - Controls `chrony_manage_service` for the `chrony` role.
        required: false
        type: bool
      chrony_service_enabled:
        description:
        - Controls `chrony_service_enabled` for the `chrony` role.
        required: false
        type: bool
      chrony_service_state:
        description:
        - Controls `chrony_service_state` for the `chrony` role.
        required: false
        type: str
      chrony_servers:
        description:
        - Controls `chrony_servers` for the `chrony` role.
        required: false
        type: list
        elements: str
      chrony_allowed:
        description:
        - Controls `chrony_allowed` for the `chrony` role.
        required: false
        type: list
        elements: str
