---
chrony_set_time_zone: true
chrony_timezone: 'Europe/Berlin'
chrony_manage_ntp: true
chrony_manage_service: true
chrony_service_enabled: true
chrony_service_state: started
chrony_servers:
- 0.de.pool.ntp.org
- 1.de.pool.ntp.org
- 2.de.pool.ntp.org
- 3.de.pool.ntp.org
chrony_allowed:
- 127.0.0.1
- ::1
