---
# RedHat/Rocky/CentOS specific variables
certbot_packages_base:
- certbot
- python3-pip

certbot_dns_provider_packages:
  cloudflare:
    - python3-certbot-dns-cloudflare
  hetzner: []

# Package manager specific settings
certbot_package_manager: dnf
certbot_update_cache: false

# Additional repositories might be needed for certbot on RHEL-based systems
certbot_enable_epel: true
