---
- name: Apply netplan config
  ansible.builtin.command:
    cmd: "/usr/sbin/netplan apply"
  listen: netplan apply config
  changed_when: true
  when: netplan_manage_service | bool
  become: true
  tags: network

- name: Generate netplan config
  ansible.builtin.command:
    cmd: "/usr/sbin/netplan generate"
  listen: Generate netplan config
  changed_when: true
  notify: Apply netplan config
  become: true
  tags: network
