---
argument_specs:
  main:
    short_description: Entry point for the firewalld role.
    description:
    - Validate variables for the `firewalld` role.
    options:
      firewalld_defaults_rules:
        description:
        - Controls `firewalld_defaults_rules` for the `firewalld` role.
        required: false
        type: list
        elements: dict
      firewalld_defaults_custom_zones:
        description:
        - Controls `firewalld_defaults_custom_zones` for the `firewalld` role.
        required: false
        type: list
      firewalld_defaults_zones:
        description:
        - Controls `firewalld_defaults_zones` for the `firewalld` role.
        required: false
        type: list
      firewalld_defaults_services:
        description:
        - Controls `firewalld_defaults_services` for the `firewalld` role.
        required: false
        type: list
      firewalld_group_vars_services:
        description:
        - Controls `firewalld_group_vars_services` for the `firewalld` role.
        required: false
        type: list
      firewalld_group_vars_zones:
        description:
        - Controls `firewalld_group_vars_zones` for the `firewalld` role.
        required: false
        type: list
      firewalld_group_vars_custom_zones:
        description:
        - Controls `firewalld_group_vars_custom_zones` for the `firewalld` role.
        required: false
        type: list
      firewalld_group_vars_rules:
        description:
        - Controls `firewalld_group_vars_rules` for the `firewalld` role.
        required: false
        type: list
      firewalld_host_vars_services:
        description:
        - Controls `firewalld_host_vars_services` for the `firewalld` role.
        required: false
        type: list
      firewalld_host_vars_zones:
        description:
        - Controls `firewalld_host_vars_zones` for the `firewalld` role.
        required: false
        type: list
      firewalld_host_vars_custom_zones:
        description:
        - Controls `firewalld_host_vars_custom_zones` for the `firewalld` role.
        required: false
        type: list
      firewalld_host_vars_rules:
        description:
        - Controls `firewalld_host_vars_rules` for the `firewalld` role.
        required: false
        type: list
      firewalld_playbook_services:
        description:
        - Controls `firewalld_playbook_services` for the `firewalld` role.
        required: false
        type: list
      firewalld_playbook_zones:
        description:
        - Controls `firewalld_playbook_zones` for the `firewalld` role.
        required: false
        type: list
      firewalld_playbook_custom_zones:
        description:
        - Controls `firewalld_playbook_custom_zones` for the `firewalld` role.
        required: false
        type: list
      firewalld_playbook_rules:
        description:
        - Controls `firewalld_playbook_rules` for the `firewalld` role.
        required: false
        type: list
