---
argument_specs:
  main:
    short_description: Entry point for the sysctl role.
    description:
    - Validate variables for the `sysctl` role.
    options:
      sysctl_defaults:
        description:
        - Controls `sysctl_defaults` for the `sysctl` role.
        required: false
        type: dict
      sysctl_group_vars:
        description:
        - Controls `sysctl_group_vars` for the `sysctl` role.
        required: false
        type: dict
      sysctl_host_vars:
        description:
        - Controls `sysctl_host_vars` for the `sysctl` role.
        required: false
        type: dict
      sysctl_playbook:
        description:
        - Controls `sysctl_playbook` for the `sysctl` role.
        required: false
        type: dict
