---
argument_specs:
  main:
    short_description: Entry point for the nmcli role.
    description:
    - Validate variables for the `nmcli` role.
    options:
      nmcli_default_iface:
        description:
        - Controls `nmcli_default_iface` for the `nmcli` role.
        required: false
        type: str
      nmcli_default_gateway:
        description:
        - Controls `nmcli_default_gateway` for the `nmcli` role.
        required: false
        type: str
      nmcli_default_address:
        description:
        - Controls `nmcli_default_address` for the `nmcli` role.
        required: false
        type: str
      nmcli_default_netmask:
        description:
        - Controls `nmcli_default_netmask` for the `nmcli` role.
        required: false
        type: str
      nmcli_default_cidr:
        description:
        - Controls `nmcli_default_cidr` for the `nmcli` role.
        required: false
        type: str
      nmcli_interfaces:
        description:
        - Controls `nmcli_interfaces` for the `nmcli` role.
        required: false
        type: list
        elements: dict
