---
k3s_proxmox_backup_target_host: pve.lenmail.de
k3s_proxmox_backup_target_user: lenadmin
k3s_proxmox_backup_job_id: platform-bus-k3s
k3s_proxmox_backup_storage: pbs.lenmail.de
k3s_proxmox_backup_schedule: "02:30"
k3s_proxmox_backup_mode: snapshot
k3s_proxmox_backup_repeat_missed: true
k3s_proxmox_backup_prune: "keep-daily=7,keep-weekly=4,keep-monthly=6"
k3s_proxmox_backup_comment: Managed by ansible-infra-lenmail
k3s_proxmox_backup_vm_names: []
