---
docker_apt_keyring_path: /etc/apt/keyrings/docker.asc
docker_apt_repository_suite: "{{ ansible_distribution_release }}"
docker_apt_repository_url: https://download.docker.com/linux/debian
docker_conflicting_packages:
- docker.io
- docker-compose
- docker-doc
- podman-docker
- containerd
- runc
docker_repository_gpg_key_url: https://download.docker.com/linux/debian/gpg
docker_repository_prerequisite_packages:
- ca-certificates
- curl
