---
argument_specs:
  main:
    short_description: Entry point for the netplan role.
    description:
    - Validate variables for the `netplan` role.
    options:
      netplan_file:
        description:
        - Controls `netplan_file` for the `netplan` role.
        required: false
        type: str
      netplan_path:
        description:
        - Controls `netplan_path` for the `netplan` role.
        required: false
        type: str
      netplan_config:
        description:
        - Controls `netplan_config` for the `netplan` role.
        required: false
        type: dict
      netplan_enabled:
        description:
        - Controls `netplan_enabled` for the `netplan` role.
        required: false
        type: bool
      netplan_packages:
        description:
        - Controls `netplan_packages` for the `netplan` role.
        required: false
        type: list
        elements: str
      netplan_renderer:
        description:
        - Controls `netplan_renderer` for the `netplan` role.
        required: false
        type: str
      netplan_version:
        description:
        - Controls `netplan_version` for the `netplan` role.
        required: false
        type: int
      netplan_wipe:
        description:
        - Controls `netplan_wipe` for the `netplan` role.
        required: false
        type: bool
