---
argument_specs:
  main:
    short_description: Entry point for the users role.
    description:
    - Validate variables for the `users` role.
    options:
      users_defaults:
        description:
        - Controls `users_defaults` for the `users` role.
        required: false
        type: list
      users_manage_root_dotfiles:
        description:
        - Controls `users_manage_root_dotfiles` for the `users` role.
        required: false
        type: bool
      users_copy_msmtp_config:
        description:
        - Controls `users_copy_msmtp_config` for the `users` role.
        required: false
        type: bool
