---
- name: Create directories for NFS exports
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
  loop: "{{ nfs_exports }}"
  when: item.create is not defined or item.create

- name: Configure NFS exports
  ansible.builtin.blockinfile:
    path: /etc/exports
    marker: "# {mark}: Ansible-managed NFS exports"
    content: |
      {% for export in nfs_exports %}
      {{ export.path }} {{ export.exports | join(" ") }}
      {% endfor %}
  notify: reload nfs

- name: Configure the NFS server daemon
  ansible.builtin.service:
    name: "{{ nfs_server_daemon }}"
    state: "{{ 'started' if nfs_exports else 'stopped' }}"
    enabled: "{{ nfs_exports | bool }}"

- name: Reload NFS exports
  meta: flush_handlers
