---
argument_specs:
  main:
    short_description: Entry point for the auditd role.
    description:
    - Validate variables for the `auditd` role.
    options:
      auditd_manage_service:
        description:
        - Controls `auditd_manage_service` for the `auditd` role.
        required: false
        type: bool
      auditd_service_enabled:
        description:
        - Controls `auditd_service_enabled` for the `auditd` role.
        required: false
        type: bool
      auditd_service_state:
        description:
        - Controls `auditd_service_state` for the `auditd` role.
        required: false
        type: str
      auditd_extra_rules:
        description:
        - Controls `auditd_extra_rules` for the `auditd` role.
        required: false
        type: list
