---
argument_specs:
  main:
    short_description: Entry point for the sshd role.
    description:
    - Validate variables for the `sshd` role.
    options:
      sshd_manage_service:
        description:
        - Controls `sshd_manage_service` for the `sshd` role.
        required: false
        type: bool
      sshd_service_enabled:
        description:
        - Controls `sshd_service_enabled` for the `sshd` role.
        required: false
        type: bool
      sshd_service_state:
        description:
        - Controls `sshd_service_state` for the `sshd` role.
        required: false
        type: str
      sshd_manage_firewall:
        description:
        - Controls `sshd_manage_firewall` for the `sshd` role.
        required: false
        type: bool
      sshd_firewall_zone:
        description:
        - Controls `sshd_firewall_zone` for the `sshd` role.
        required: false
        type: str
      sshd_manage_selinux:
        description:
        - Controls `sshd_manage_selinux` for the `sshd` role.
        required: false
        type: bool
      sshd_bind_ips:
        description:
        - Controls `sshd_bind_ips` for the `sshd` role.
        required: false
        type: bool
      sshd_client_defaults:
        description:
        - Controls `sshd_client_defaults` for the `sshd` role.
        required: false
        type: dict
      sshd_client_group_vars:
        description:
        - Controls `sshd_client_group_vars` for the `sshd` role.
        required: false
        type: dict
      sshd_client_host_vars:
        description:
        - Controls `sshd_client_host_vars` for the `sshd` role.
        required: false
        type: dict
      sshd_client_playbook:
        description:
        - Controls `sshd_client_playbook` for the `sshd` role.
        required: false
        type: dict
      sshd_server_defaults:
        description:
        - Controls `sshd_server_defaults` for the `sshd` role.
        required: false
        type: dict
      sshd_server_group_vars:
        description:
        - Controls `sshd_server_group_vars` for the `sshd` role.
        required: false
        type: dict
      sshd_server_host_vars:
        description:
        - Controls `sshd_server_host_vars` for the `sshd` role.
        required: false
        type: dict
      sshd_server_playbook:
        description:
        - Controls `sshd_server_playbook` for the `sshd` role.
        required: false
        type: dict
