---
proxy_env: {}
squid_manage_service: true
squid_service_enabled: true
squid_service_state: started
squid_manage_firewall: false
squid_port: 3128
squid_config_dir: /etc/squid
squid_conf_d_dir: /etc/squid/conf.d
squid_user: squid
squid_group: squid
squid_visible_hostname: "{{ ansible_fqdn | default(ansible_hostname) }}"
squid_cache_mgr: "hostmaster@{{ ansible_domain | default('localdomain') }}"
squid_ssl_ports:
- 443
squid_safe_ports:
- 80
- 443
squid_acl_files: []
squid_acl_definitions: []
squid_http_access_rules: []
squid_extra_config: []
