---
sftp_server_package_name: openssh-server
sftp_server_service_name: ssh
sftp_server_sshd_config_dir: /etc/ssh/sshd_config.d
sftp_server_sshd_match_config_path: /etc/ssh/sshd_config.d/99-sftp-server.conf
