---
argument_specs:
  main:
    short_description: Entry point for the interfaces role.
    description:
    - Validate variables for the `interfaces` role.
    options:
      interfaces_config:
        description:
        - Controls `interfaces_config` for the `interfaces` role.
        required: false
        type: list
        elements: dict
