---
argument_specs:
  main:
    short_description: Entry point for the gui role.
    description:
      - Install a graphical desktop environment and set the graphical systemd target.
    options:
      gui_enabled:
        type: bool
        default: false
      gui_redhat_group_name:
        type: str
        default: "Server with GUI"
      gui_redhat_packages:
        type: list
        elements: str
        default:
          - firefox
      gui_debian_packages:
        type: list
        elements: str
        default:
          - task-xfce-desktop
          - firefox-esr
      gui_default_target:
        type: str
        default: graphical.target
