---
galaxy_info:
  author: Dominik Lenhardt
  description: Install a graphical desktop environment on supported Linux hosts.
  license: MIT
  min_ansible_version: '2.16'
  platforms:
  - name: Debian
    versions:
    - bookworm
  - name: Ubuntu
    versions:
    - jammy
    - noble
  - name: EL
    versions:
    - '9'
  galaxy_tags:
  - desktop
  - gui
  - linux
  - infrastructure
dependencies: []
