---
- name: Validate supported platforms
  ansible.builtin.assert:
    that:
      - ansible_os_family == "Debian"
    fail_msg: "The systemd_timesyncd role currently supports Debian and Ubuntu systems only."
  tags: timesyncd

- name: Configure /etc/timezone
  ansible.builtin.copy:
    content: "{{ systemd_timesyncd_time_zone }}\n"
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
  tags: timesyncd

- name: Configure /etc/systemd/timesyncd.conf
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart systemd-timesyncd
  when: systemd_timesyncd
  tags: timesyncd

- name: Start and enable systemd time services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - systemd-timedated
    - systemd-timesyncd
  when: systemd_timesyncd
  tags: timesyncd
