---
argument_specs:
  main:
    short_description: Entry point for the ufw role.
    description:
    - Validate variables for the `ufw` role.
    options:
      ufw_rules_defaults:
        description:
        - Controls `ufw_rules_defaults` for the `ufw` role.
        required: false
        type: list
        elements: dict
      ufw_rules_group_vars:
        description:
        - Controls `ufw_rules_group_vars` for the `ufw` role.
        required: false
        type: list
      ufw_rules_host_vars:
        description:
        - Controls `ufw_rules_host_vars` for the `ufw` role.
        required: false
        type: list
      ufw_rules_playbook:
        description:
        - Controls `ufw_rules_playbook` for the `ufw` role.
        required: false
        type: list
      ufw_enabled:
        description:
        - Controls `ufw_enabled` for the `ufw` role.
        required: false
        type: bool
      ufw_policy:
        description:
        - Controls `ufw_policy` for the `ufw` role.
        required: false
        type: str
      ufw_manage_config:
        description:
        - Controls `ufw_manage_config` for the `ufw` role.
        required: false
        type: bool
      ufw_config:
        description:
        - Controls `ufw_config` for the `ufw` role.
        required: false
        type: dict
