---
argument_specs:
  main:
    short_description: Entry point for the nfs role.
    description:
    - Validate variables for the `nfs` role.
    options:
      nfs_manage_service:
        description:
        - Controls `nfs_manage_service` for the `nfs` role.
        required: false
        type: bool
      nfs_service_enabled:
        description:
        - Controls `nfs_service_enabled` for the `nfs` role.
        required: false
        type: bool
      nfs_service_state:
        description:
        - Controls `nfs_service_state` for the `nfs` role.
        required: false
        type: str
      nfs_exports:
        description:
        - Controls `nfs_exports` for the `nfs` role.
        required: false
        type: list
      nfs_mounts:
        description:
        - Controls `nfs_mounts` for the `nfs` role.
        required: false
        type: list
