---
argument_specs:
  main:
    short_description: Entry point for the packages role.
    description:
    - Validate variables for the `packages` role.
    options:
      packages_epel_release:
        description:
        - Controls `packages_epel_release` for the `packages` role.
        required: false
        type: bool
      packages_manage_cache:
        description:
        - Controls `packages_manage_cache` for the `packages` role.
        required: false
        type: bool
      packages_group_vars_install:
        description:
        - Controls `packages_group_vars_install` for the `packages` role.
        required: false
        type: list
      packages_group_vars_install_epel:
        description:
        - Controls `packages_group_vars_install_epel` for the `packages` role.
        required: false
        type: list
      packages_group_vars_remove:
        description:
        - Controls `packages_group_vars_remove` for the `packages` role.
        required: false
        type: list
      packages_host_vars_install:
        description:
        - Controls `packages_host_vars_install` for the `packages` role.
        required: false
        type: list
      packages_host_vars_install_epel:
        description:
        - Controls `packages_host_vars_install_epel` for the `packages` role.
        required: false
        type: list
      packages_host_vars_remove:
        description:
        - Controls `packages_host_vars_remove` for the `packages` role.
        required: false
        type: list
      packages_playbook_install:
        description:
        - Controls `packages_playbook_install` for the `packages` role.
        required: false
        type: list
      packages_playbook_install_epel:
        description:
        - Controls `packages_playbook_install_epel` for the `packages` role.
        required: false
        type: list
      packages_playbook_remove:
        description:
        - Controls `packages_playbook_remove` for the `packages` role.
        required: false
        type: list
