---
borgmatic_binary_path: /usr/local/bin/borgmatic
borgmatic_package_names:
- borgbackup
- python3
- ca-certificates
borgmatic_python_interpreter: /usr/bin/python3
borgmatic_repository_default_encryption: none
borgmatic_service_unit_name: borgmatic.service
borgmatic_timer_unit_name: borgmatic.timer
borgmatic_uv_binary_path: /usr/local/bin/uv
borgmatic_uv_cache_dir: /var/cache/uv
borgmatic_uv_install_dir: /usr/local/bin
borgmatic_uv_installer_url: https://astral.sh/uv/install.sh
borgmatic_uv_tool_bin_dir: /usr/local/bin
borgmatic_uv_tool_dir: /opt/borgmatic/uv-tools
