---
sssd_sshd_service_name: ssh
sssd_packages:
- realmd
- sssd
- sssd-tools
- samba-common
- krb5-user
- packagekit
- samba-common-bin
- samba-libs
- adcli
- chrony
- python3-pexpect
sssd_realm_binary: /usr/sbin/realm
sssd_oddjob_service_name: oddjobd
