---
unbound_packages:
- unbound
- python3-cryptography
- dns-root-data
unbound_service_name: unbound
unbound_group: unbound
unbound_config_dir: /etc/unbound
unbound_config_path: /etc/unbound/unbound.conf
unbound_root_hints_path: /etc/unbound/root.hints
unbound_local_zones_path: /etc/unbound/local-zones.conf
unbound_blocklist_path: /etc/unbound/unbound.block.conf
unbound_tls_cert_bundle: /etc/ssl/certs/ca-certificates.crt
unbound_checkconf_binary: /usr/sbin/unbound-checkconf
